stages:
  - build
  - triggers

## Abstract job for all projects triggers
.trigger-job:
    stage: triggers
    trigger:
        strategy: depend

##################

generate-packages-pipeline:
  image: composer:2
  stage: build
  script:
    - composer install
    - php .gitlab/generate-dynamic-pipeline.php
    - cat .gitlab/.gitlab-dynamic-children.yml
  rules:
    - if: $CI_MERGE_REQUEST_ID || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - packages/**/*
  artifacts:
    paths:
      - .gitlab/.gitlab-dynamic-children.yml

packages:
  extends: .trigger-job
  rules:
    - if: $CI_MERGE_REQUEST_ID || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - packages/**/*
  trigger:
    include:
      - artifact: .gitlab/.gitlab-dynamic-children.yml
        job: generate-packages-pipeline
