stages:
  - build
  - triggers

##################

generate-packages-ci-file:
  image: php:8
  stage: build
  script:
    - echo "Running composer install etc ..."
    - php .gitlab/generate-packages-pipelines.php
    - cat .gitlab/generated-gitlab-ci.yml
  artifacts:
    paths:
      - .gitlab/generated-gitlab-ci.yml

##

trigger-packages:
  stage: triggers
  trigger:
    include:
      - artifact: .gitlab/generated-gitlab-ci.yml
        job: generate-packages-ci-file
