stages:
  - build
  - test
  - deploy

##################

composer:
  stage: build
  script:
    - echo "Run composer install for example .."

##

package-a-tests:
  stage: test
  script:
    - echo "Test package A - running 'vendor/bin/phpunit tests packages/A/tests'"

package-b-tests:
  stage: test
  script:
    - echo "Test package B - running 'vendor/bin/phpunit tests packages/B/tests'"

package-c-tests:
  stage: test
  script:
    - echo "Test package C - running 'vendor/bin/phpunit tests packages/C/tests'"

##

package-a-deploy:
  stage: deploy
  script:
    - echo "Deploy package A .. publish it somewhere .."

package-b-deploy:
  stage: deploy
  script:
    - echo "Deploy package B .. publish it somewhere .."

package-c-deploy:
  stage: deploy
  script:
    - echo "Deploy package C .. publish it somewhere .."
