stages:
  - build
  - triggers

##################

generate-packages-ci-file:
  image: composer:2
  stage: build
  script:
    - composer install
    - php .gitlab/generate-packages-pipelines-dependencies.php
    - cat .gitlab/generated-gitlab-ci.yml
  artifacts:
    paths:
      - .gitlab/generated-gitlab-ci.yml
  rules:
    - if: $CI_MERGE_REQUEST_ID || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

##

trigger-packages:
  stage: triggers
  trigger:
    include:
      - artifact: .gitlab/generated-gitlab-ci.yml
        job: generate-packages-ci-file
  rules:
    - if: $CI_MERGE_REQUEST_ID || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - packages/**/*
