stages:
  - build
  - triggers

##################

composer:
  stage: build
  script:
    - echo "Run composer install for example .."

##

package-a:
  stage: triggers
  trigger:
    include: "packages/A/.gitlab-ci.yml"
    strategy: depend
  rules:
    - if: $CI_MERGE_REQUEST_ID || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - packages/A/**/*

package-b:
  stage: triggers
  trigger:
    include: "packages/B/.gitlab-ci.yml"
    strategy: depend
  rules:
    - if: $CI_MERGE_REQUEST_ID || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - packages/B/**/*

package-c:
  stage: triggers
  trigger:
    include: "packages/C/.gitlab-ci.yml"
    strategy: depend
  rules:
    - if: $CI_MERGE_REQUEST_ID || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - packages/C/**/*
