include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

stages:
  - test
  - deploy

##################

tests:
  stage: test
  script:
    - echo "Test package 'vendor/bin/phpunit tests"

deploy:
  stage: deploy
  script:
    - echo "Deploy publish it somewhere .."
